## Sections

- [Constructing our first tensors](#Constructing-our-first-tensors)
- [The essence of tensors](#The-essence-of-tensors)
- [Indexing tensors](#Indexing-tensors)
- [Broadcasting](#Broadcasting)
- [Tensor element types](#Tensor-element-types)

# Constructing our first tensors

In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
a[2] = 2.0
a

tensor([1., 1., 2.])

# The essence of tensors

In [6]:
points = torch.zeros(6)

print(points)

points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

print(points)

tensor([0., 0., 0., 0., 0., 0.])
tensor([4., 1., 5., 3., 2., 1.])


In [7]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [9]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points.shape

torch.Size([3, 2])

In [11]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points[0, 1]

tensor(1.)

In [14]:
points[0]

tensor([4., 1.])

# Indexing tensors

In [15]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
points

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [16]:
points[1:] # All rows after the first; implicitly all columns

tensor([[3., 4.],
        [5., 6.]])

In [17]:
points[1:, :] # All rows after the first; all columns

tensor([[3., 4.],
        [5., 6.]])

In [18]:
points[1:, 0] # All rows after the first; first column

tensor([3., 5.])

In [19]:
points[None] # Adds a dimension of size 1; the same can be accomplished with points.unsqueeze(dim=0)

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

# Broadcasting

In [20]:
points = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
points

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [21]:
points + torch.tensor([10.0, 20.0])  # 1D tensor (2,) is broadcast to match points' shape (3, 2)

tensor([[11., 22.],
        [13., 24.],
        [15., 26.]])

In [22]:
a = torch.tensor([[1.0, 2.0, 3.0]])       # shape (1, 3)
b = torch.tensor([[1.0], [2.0], [3.0]])   # shape (3, 1)
a * b  # Both dimensions are 1 on one side, so it broadcasts to shape (3, 3)

tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])

# Tensor element types

In [23]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [24]:
short_points.dtype

torch.int16

In [25]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [26]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [27]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)