## Sections

- [Constructing our first tensors](#Constructing-our-first-tensors)
- [The essence of tensors](#The-essence-of-tensors)

# Constructing our first tensors

In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
a[2] = 2.0
a

tensor([1., 1., 2.])

# The essence of tensors

In [6]:
points = torch.zeros(6)

print(points)

points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

print(points)

tensor([0., 0., 0., 0., 0., 0.])
tensor([4., 1., 5., 3., 2., 1.])


In [7]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [9]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points.shape

torch.Size([3, 2])

In [11]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points[0, 1]

tensor(1.)

In [14]:
points[0]

tensor([4., 1.])